"use strict";
// import { User } from 'src/auth/entities/User.entity';
Object.defineProperty(exports, "__esModule", { value: true });
exports.ContentTypes = exports.FileUploadExtensions = void 0;
var FileUploadExtensions;
(function (FileUploadExtensions) {
    FileUploadExtensions["PDF"] = "pdf";
    FileUploadExtensions["WORD_DOC"] = "doc";
    FileUploadExtensions["WORD_DOCX"] = "docx";
    FileUploadExtensions["IMAGE_PNG"] = "png";
    FileUploadExtensions["IMAGE_JPG"] = "jpg";
    FileUploadExtensions["IMAGE_JPGEG"] = "jpeg";
    FileUploadExtensions["IMAGE_GIF"] = "gif";
    FileUploadExtensions["IMAGE_WEBP"] = "webp";
    FileUploadExtensions["VIDEO_MP4"] = "mp4";
    FileUploadExtensions["VIDEO_WEBM"] = "webm";
    FileUploadExtensions["VIDEO_MKV"] = "mkv";
    FileUploadExtensions["VIDEO_3GP"] = "3gp";
    FileUploadExtensions["VIDEO_AVI"] = "avi";
    FileUploadExtensions["VIDEO_WMV"] = "wmv";
    FileUploadExtensions["VIDEO_MOV"] = "mov";
    FileUploadExtensions["VIDEO_M3U8"] = "m3u8";
    FileUploadExtensions["VIDEO_TS"] = "ts";
    FileUploadExtensions["VIDEO_FLV"] = "flv";
})(FileUploadExtensions || (exports.FileUploadExtensions = FileUploadExtensions = {}));
var ContentTypes;
(function (ContentTypes) {
    ContentTypes["PDF"] = "application/pdf";
    ContentTypes["WORD_DOC"] = "application/msword";
    ContentTypes["WORD_DOCX"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    ContentTypes["IMAGE_PNG"] = "image/png";
    ContentTypes["IMAGE_JPG"] = "image/jpeg";
    ContentTypes["IMAGE_JPGEG"] = "image/jpeg";
    ContentTypes["IMAGE_GIF"] = "image/gif";
    ContentTypes["IMAGE_WEBP"] = "image/webp";
    ContentTypes["VIDEO_MP4"] = "video/mp4";
    ContentTypes["VIDEO_WEBM"] = "video/webm";
    ContentTypes["VIDEO_MKV"] = "video/x-matroska";
    ContentTypes["VIDEO_3GP"] = "video/3gpp";
    ContentTypes["VIDEO_AVI"] = "video/x-msvideo";
    ContentTypes["VIDEO_WMV"] = "video/x-ms-wmv";
    ContentTypes["VIDEO_MOV"] = "video/quicktime";
    ContentTypes["VIDEO_M3U8"] = "application/x-mpegURL";
    ContentTypes["VIDEO_TS"] = "video/MP2T";
    ContentTypes["VIDEO_FLV"] = "video/x-flv";
})(ContentTypes || (exports.ContentTypes = ContentTypes = {}));
